# .github/workflows/ci-behave.yml

name: CI/CD - Behave UI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify your Python version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y allure-commandline

    - name: Run Behave tests and generate raw Allure results
      run: behave -f allure_behave.formatter:AllureFormatter -o allure-results/ ./features/ || true

    - name: Generate and Deploy Allure Report to GitHub Pages
      # --- FIX IS HERE ---
      # Use a specific existing version tag like v2.10.0 (or check GitHub Marketplace for latest recommended v2.x.y)
      uses: allure-framework/allure-action@v2.10.0 # <--- CORRECTED VERSION TAG
      if: always()
      with:
        allure_results_folder: allure-results
        allure_report_folder: allure-report
        allure_history_folder: allure-history
        github_token: ${{ secrets.GITHUB_TOKEN }}
        allure_report_url: https://your-username.github.io/Project-SauceDemo/ # <--- ***UPDATE THIS LINE***
        keep_history: true
        
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload Allure Report Artifact for Pages Deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
