# .github/workflows/ci-behave.yml

name: CI/CD - Behave UI Tests

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies & Allure Commandline
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        sudo apt-get update                                 
        sudo apt-get install -y software-properties-common   
        sudo add-apt-repository ppa:qameta/allure           
        sudo apt-get update                                  
        sudo apt-get install -y allure-commandline

    - name: Run Behave tests and generate raw Allure results
      run: behave -f allure_behave.formatter:AllureFormatter -o allure-results/ ./features/ || true

    - name: Generate Allure HTML Report
      run: allure generate --clean allure-results/ -o allure-report/
      if: always()

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload Allure Report Artifact for Pages Deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
