# .github/workflows/ci-behave.yml

name: CI/CD - Behave UI Tests

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-22.04 # This is now correctly set to 22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies & Allure Commandline
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt      
        
        ALLURE_VERSION="2.34.1" # Correct version
        # --- FIX: Correct the download URL format ---
        ALLURE_DOWNLOAD_URL="https://github.com/allure-framework/allure2/releases/download/allure-${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip" # <--- UPDATED THIS LINE
        # --------------------------------------------
        ALLURE_INSTALL_DIR="${HOME}/allure-commandline"
        
        echo "Downloading Allure Commandline from ${ALLURE_DOWNLOAD_URL}..."
        curl -fsSL --retry 5 --retry-delay 5 "${ALLURE_DOWNLOAD_URL}" -o allure.zip
        
        if [ ! -s "allure.zip" ]; then
          echo "Error: allure.zip was not downloaded successfully or is empty."
          exit 1
        fi
        
        mkdir -p "${ALLURE_INSTALL_DIR}"
        unzip allure.zip -d "${ALLURE_INSTALL_DIR}"
        
        echo "${ALLURE_INSTALL_DIR}/allure-commandline-${ALLURE_VERSION}/bin" >> $GITHUB_PATH
        echo "Allure Commandline ${ALLURE_VERSION} installed to ${ALLURE_INSTALL_DIR}"

    - name: Run Behave tests and generate raw Allure results
      run: behave -f allure_behave.formatter:AllureFormatter -o allure-results/ ./features/ || true

    - name: Generate Allure HTML Report
      run: allure generate --clean allure-results/ -o allure-report/
      if: always()

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload Allure Report Artifact for Pages Deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
