name: CI/CD - Behave UI Tests

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure Commandline
      run: |
        ALLURE_VERSION=2.24.1
        ALLURE_URL="https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.zip"
        
        echo "Downloading Allure from $ALLURE_URL"
        curl -L "$ALLURE_URL" -o allure.zip
        unzip allure.zip -d allure
        echo "$GITHUB_WORKSPACE/allure/bin" >> $GITHUB_PATH
        rm allure.zip

    - name: Run Behave tests
      run: |
        behave -f allure_behave.formatter:AllureFormatter -o allure-results/ ./features/ || true

    - name: Generate Allure report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report
        allure open allure-report

    - name: Upload Allure report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        retention-days: 7

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4
